import type { Client, Tax, Obligation, Installment } from "./types";

export const createClient = (overrides: Partial<Client> = {}): Client => ({
  id: crypto.randomUUID(),
  name: "",
  cnpj: "",
  email: "",
  phone: "",
  status: "active",
  taxRegime: "Simples Nacional",
  createdAt: new Date().toISOString(),
  ...overrides,
});

export const createTax = (overrides: Partial<Tax> = {}): Tax => ({
  id: crypto.randomUUID(),
  name: "",
  description: "",
  federalTaxCode: "",
  clientId: undefined,
  dueDay: 10,
  dueMonth: undefined,
  recurrence: "monthly",
  recurrenceInterval: 1,
  autoGenerate: false,
  weekendRule: "postpone",
  notes: "",
  tags: [],
  createdAt: new Date().toISOString(),
  ...overrides,
});

export const createObligation = (overrides: Partial<Obligation> = {}): Obligation => ({
  id: crypto.randomUUID(),
  name: "",
  description: "",
  category: "other",
  clientId: "",
  taxId: undefined,
  dueDay: 10,
  dueMonth: undefined,
  frequency: "monthly",
  recurrence: "monthly",
  recurrenceInterval: 1,
  recurrenceEndDate: undefined,
  autoGenerate: false,
  weekendRule: "postpone",
  status: "pending",
  priority: "medium",
  assignedTo: undefined,
  protocol: undefined,
  realizationDate: undefined,
  notes: "",
  createdAt: new Date().toISOString(),
  completedAt: undefined,
  completedBy: undefined,
  attachments: [],
  history: [],
  parentObligationId: undefined,
  generatedFor: undefined,
  tags: [],
  ...overrides,
});

export const createInstallment = (overrides: Partial<Installment> = {}): Installment => ({
  id: crypto.randomUUID(),
  name: "",
  description: "",
  clientId: "",
  installmentNumber: 1,
  totalInstallments: 1,
  dueDay: 10,
  dueMonth: undefined,
  recurrence: "monthly",
  recurrenceInterval: 1,
  recurrenceEndDate: undefined,
  autoGenerate: false,
  weekendRule: "postpone",
  status: "pending",
  notes: "",
  tags: [],
  createdAt: new Date().toISOString(),
  completedAt: undefined,
  completedBy: undefined,
  parentObligationId: undefined,
  generatedFor: undefined,
  ...overrides,
});