// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ihwmsjfnpirlfcuptima.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod21zamZucGlybGZjdXB0aW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NzM3MTEsImV4cCI6MjA3NjA0OTcxMX0.ypLuY922CoMxsoTMpZb8BEYRU9jusHVrDYpp_aMx3R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);